### ISSUE TITLE
Display 856 url in document view

### ISSUE THREAD

**Issue by jsteverman** [HTGovdocs/usdocs_registry#7]
856 is frequently a url to a linked resource. 

This may be impossible due to links to non-public services.

**Comment by jsteverman** [comment]
Currently showing 856 urls if they match /purl/. This is a bit of a kludge and is located in the _show_default template. This should be handled elsewhere, a helper? should_show_856?

**Comment by billdueber** [comment]
I'd have a method that takes a document and returns a list of links to be displayed. Then you can just call that method and keep everything internal to it (including, say, whether the link is sitting in an 856, or you're creating it from a 974 hathi line, or whatever).

**Comment by jsteverman** [comment]
The 856 and oclc link stuff has been moved to applicationHelper.  The HT links are still generated in template.
